const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

exports.getAll = async (req, res) => {
  try {
    const configurations = await prisma.configuration.findMany({
      orderBy: { updatedAt: 'desc' }
    });
    res.json({ success: true, count: configurations.length, data: configurations });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

exports.getById = async (req, res) => {
  try {
    const config = await prisma.configuration.findUnique({ where: { id: req.params.id } });
    if (!config) return res.status(404).json({ success: false, error: 'Configuration not found' });
    res.json({ success: true, data: config });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

exports.create = async (req, res) => {
  try {
    const config = await prisma.configuration.create({ data: req.body });
    res.status(201).json({ success: true, data: config });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

exports.update = async (req, res) => {
  try {
    const config = await prisma.configuration.update({
      where: { id: req.params.id },
      data: req.body
    });
    res.json({ success: true, data: config });
  } catch (error) {
    if (error.code === 'P2025') {
      return res.status(404).json({ success: false, error: 'Configuration not found' });
    }
    res.status(400).json({ success: false, error: error.message });
  }
};

exports.delete = async (req, res) => {
  try {
    await prisma.configuration.delete({ where: { id: req.params.id } });
    res.json({ success: true, message: 'Configuration deleted successfully' });
  } catch (error) {
    if (error.code === 'P2025') {
      return res.status(404).json({ success: false, error: 'Configuration not found' });
    }
    res.status(500).json({ success: false, error: error.message });
  }
};

exports.exportConfig = async (req, res) => {
  try {
    const config = await prisma.configuration.findUnique({ where: { id: req.params.id } });
    if (!config) return res.status(404).json({ success: false, error: 'Configuration not found' });

    // Generate proper CLAUDE.md markdown format
    const claudeMd = generateClaudeMD(config);

    res.setHeader('Content-Type', 'text/markdown');
    res.setHeader('Content-Disposition', 'attachment; filename="CLAUDE.md"');
    res.send(claudeMd);
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

/**
 * Generate CLAUDE.md markdown content from configuration
 */
function generateClaudeMD(config) {
  const data = config.data || {};
  const sections = data.sections || [];

  let content = '# CLAUDE.md - Configuration\n\n';
  content += '<!-- Generated by Claude Commander -->\n';
  content += `<!-- Generated: ${new Date().toISOString()} -->\n`;
  content += `<!-- Config: ${config.name || 'Unnamed'} -->\n\n`;
  content += '---\n\n';

  // Filter enabled sections and sort by priority
  const enabledSections = sections
    .filter(s => s.enabled !== false)
    .sort((a, b) => (a.priority || 2) - (b.priority || 2));

  if (enabledSections.length === 0) {
    content += '*No sections configured.*\n';
    return content;
  }

  enabledSections.forEach(section => {
    // Add context comment if not 'all'
    if (section.context && !section.context.includes('all') && section.context.length > 0) {
      content += `<!-- Context: ${section.context.join(', ')} -->\n`;
    }

    content += `## ${section.title}\n\n`;
    content += `${section.content || ''}\n\n`;

    // Handle subsections if present
    if (section.subsections && section.subsections.length > 0) {
      section.subsections.forEach(subsection => {
        content += `### ${subsection.title}\n\n`;
        content += `${subsection.content || ''}\n\n`;
      });
    }
  });

  return content;
}

exports.createSnapshot = async (req, res) => {
  try {
    const config = await prisma.configuration.findUnique({ where: { id: req.params.id } });
    if (!config) return res.status(404).json({ success: false, error: 'Configuration not found' });

    const snapshot = await prisma.snapshot.create({
      data: {
        configurationId: req.params.id,
        data: config.data,
        description: req.body.description
      }
    });
    res.status(201).json({ success: true, data: snapshot });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
};

exports.getSnapshots = async (req, res) => {
  try {
    const snapshots = await prisma.snapshot.findMany({
      where: { configurationId: req.params.id },
      orderBy: { createdAt: 'desc' }
    });
    res.json({ success: true, count: snapshots.length, data: snapshots });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};

exports.restoreSnapshot = async (req, res) => {
  try {
    const snapshot = await prisma.snapshot.findUnique({ where: { id: req.params.snapshotId } });
    if (!snapshot) return res.status(404).json({ success: false, error: 'Snapshot not found' });

    const config = await prisma.configuration.update({
      where: { id: snapshot.configurationId },
      data: { data: snapshot.data }
    });
    res.json({ success: true, data: config });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
};
